//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirstIntro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serier
    {
        public int Id { get; set; }
        public string Navn { get; set; }
        public Nullable<int> Rang { get; set; }
        public string Producer { get; set; }
        public string UdgivelsesÅr { get; set; }
    }
}
