//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_med_Serier.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serier
    {
        public int ID { get; set; }
        public string Navn { get; set; }
        public string UdgivelsesÅr { get; set; }
        public string Instruktør { get; set; }
        public string Rating { get; set; }
    }
}
